In [11]:
import pandas as pd
import numpy as np
import datetime
import os
from sklearn.model_selection import train_test_split

from keras.models import load_model
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.callbacks import TensorBoard
import time

In [12]:
weather_data = np.load("../preprocessed_data/X_train_weather.npy")
nasdaq_data = np.load("../preprocessed_data/X_train_nasdaq.npy")
print(weather_data.shape, nasdaq_data.shape)

(1648, 20) (1648, 10)


In [13]:
base = datetime.datetime.strptime("2015-01-01", "%Y-%m-%d")
end = datetime.datetime.strptime("2019-07-06", "%Y-%m-%d")
delta = end - base
unique_PI_dates = [str(base + datetime.timedelta(days=x)).split(' ')[0] for x in range(delta.days + 1)]
print(len(unique_PI_dates))

1648


In [14]:
def crime_prediction_model():
    pass

In [15]:
pdq_list = [1.0, 3.0, 4.0, 5.0, 7.0, 8.0, 9.0, 
            10.0, 11.0, 12.0, 13.0, 15.0, 16.0, 
            20.0, 21.0, 22.0, 23.0, 24.0, 26.0, 
            27.0, 30.0, 31.0, 33.0, 35.0, 38.0, 
            39.0, 42.0, 44.0, 45.0, 46.0, 48.0, 
            49.0, 50.0, 55.0]

for pdq in pdq_list:
    pdq_filename = "pdq_" + str(int(pdq)) + '.csv'
    
    pdq_df = pd.read_csv("../datasets/" + pdq_filename, index_col='Unnamed: 0')
    target_df = np.split(pdq_df, [6], axis=1)[0]
    daytime_df = np.split(pdq_df, [6], axis=1)[1]
    
    y = target_df.to_numpy()
    X = np.concatenate((weather_data, nasdaq_data, daytime_df.to_numpy()), axis=1)
    
    print(X.shape, y.shape)
    

Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-01-01, dtype: float64
Introduction                        1.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-01-02, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            1.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-01-03, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés       

Name: 2015-09-29, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-09-30, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-10-01, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2015-10-02, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                      

Name: 2016-06-20, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2016-06-21, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2016-06-22, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2016-06-23, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                      

Name: 2017-06-09, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2017-06-10, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    1.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2017-06-11, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2017-06-12, dtype: float64
Introduction                        1.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                      

Name: 2018-03-06, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2018-03-07, dtype: float64
Introduction                        1.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2018-03-08, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2018-03-09, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                      

Name: 2019-01-08, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2019-01-09, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    1.0
Vol de véhicule à moteur            0.0
Méfait                              0.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2019-01-10, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                              1.0
Vols qualifiés                      0.0
Infractions entrainant la mort      0.0
Name: 2019-01-11, dtype: float64
Introduction                        0.0
Vol dans / sur véhicule à moteur    0.0
Vol de véhicule à moteur            0.0
Méfait                      

[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]


[1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


ValueError: 